#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=milestone2
MANUFACTURER=motorola

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/app/AudioEffectSettings.apk ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/AudioEffectSettings.apk
adb pull /system/app/CompassCalibrate.apk ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/CompassCalibrate.apk
adb pull /system/app/MotoPhonePortal.apk ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/MotoPhonePortal.apk
adb pull /system/bin/akmd2 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/akmd2
adb pull /system/bin/ap_gain.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ap_gain.bin
adb pull /system/bin/ap_gain_mmul.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ap_gain_mmul.bin
adb pull /system/bin/battd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/battd
adb pull /system/bin/brcm_guci_drv ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/brcm_guci_drv
adb pull /system/bin/charge_only_mode ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/charge_only_mode
adb pull /system/bin/gkisystem ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gkisystem
adb pull /system/bin/location ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/location
adb pull /system/bin/nvm_daemon ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/nvm_daemon
adb pull /system/bin/opprofdaemon ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/opprofdaemon
adb pull /system/bin/protocol_driver ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/protocol_driver
adb pull /system/bin/pvrsrvinit ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvinit
chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvinit
adb pull /system/bin/ssmgrd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ssmgrd
adb pull /system/bin/usbd ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usbd
adb pull /system/etc/cameraCalFileDef5M.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/cameraCalFileDef5M.bin
adb pull /system/etc/cameraCalFileDef8M.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/cameraCalFileDef8M.bin
adb pull /system/etc/firmware/wl1271.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wl1271.bin
adb pull /system/etc/fmc_init_1273.2.bts ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fmc_init_1273.2.bts
adb pull /system/etc/fmc_init_6450.2.bts ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fmc_init_6450.2.bts
adb pull /system/etc/fm_rx_init_1273.2.bts ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fm_rx_init_1273.2.bts
adb pull /system/etc/fm_rx_init_6450.2.bts ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fm_rx_init_6450.2.bts
adb pull /system/etc/mot_ise_imager_cfg.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mot_ise_imager_cfg.bin
adb pull /system/etc/motorola/ap_flex_version.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ap_flex_version.txt
adb pull /system/etc/motorola/bp_nvm_default/File_Audio ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio
adb pull /system/etc/motorola/bp_nvm_default/File_Audio1_AMR_WB ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio1_AMR_WB
adb pull /system/etc/motorola/bp_nvm_default/File_Audio2 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio2
adb pull /system/etc/motorola/bp_nvm_default/File_Audio2_AMR_WB ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio2_AMR_WB
adb pull /system/etc/motorola/bp_nvm_default/File_Audio3 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio3
adb pull /system/etc/motorola/bp_nvm_default/File_Audio3_AMR_WB ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio3_AMR_WB
adb pull /system/etc/motorola/bp_nvm_default/File_Audio4 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio4
adb pull /system/etc/motorola/bp_nvm_default/File_Audio4_AMR_WB ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio4_AMR_WB
adb pull /system/etc/motorola/bp_nvm_default/File_Audio5 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio5
adb pull /system/etc/motorola/bp_nvm_default/File_Audio5_AMR_WB ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio5_AMR_WB
adb pull /system/etc/motorola/bp_nvm_default/File_Audio6 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio6
adb pull /system/etc/motorola/bp_nvm_default/File_Audio7 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio7
adb pull /system/etc/motorola/bp_nvm_default/File_Audio8 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Audio8
adb pull /system/etc/motorola/bp_nvm_default/File_GPRS ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_GPRS
adb pull /system/etc/motorola/bp_nvm_default/File_GSM ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_GSM
adb pull /system/etc/motorola/bp_nvm_default/File_Logger ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Logger
adb pull /system/etc/motorola/bp_nvm_default/File_Seem_Flex_Tables ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_Seem_Flex_Tables
adb pull /system/etc/motorola/bp_nvm_default/File_UMA ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/File_UMA
adb pull /system/etc/motorola/comm_drv/commdrv_fs.sh ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/commdrv_fs.sh
adb pull /system/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mmins_cust_emergency_number.cfg
adb pull /system/etc/motorola/comm_drv/mmins_settings.cfg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mmins_settings.cfg
adb pull /system/etc/motorola/comm_drv/mmins_telephony.cfg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mmins_telephony.cfg
adb pull /system/etc/motorola/comm_drv/mmins_user_settings.cfg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mmins_user_settings.cfg
adb pull /system/etc/motorola/comm_drv/plmn_text_table.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/plmn_text_table.bin
adb pull /system/etc/motorola/comm_drv/PLMN_VERSION.txt ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/PLMN_VERSION.txt
adb pull /system/etc/wifi/fw_tiwlan_ap.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fw_tiwlan_ap.bin
adb pull /system/etc/wifi/fw_tiwlan_ap_rfmd.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fw_tiwlan_ap_rfmd.bin
adb pull /system/etc/wifi/fw_wlan1271.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/fw_wlan1271.bin
adb pull /system/framework/com.motorola.android.location.jar ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/com.motorola.android.location.jar
adb pull /system/lib/dsp/720p_h264vdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/720p_h264vdec_sn.dll64P
adb pull /system/lib/dsp/720p_h264venc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/720p_h264venc_sn.dll64P
adb pull /system/lib/dsp/720p_mp4vdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/720p_mp4vdec_sn.dll64P
adb pull /system/lib/dsp/720p_mp4venc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/720p_mp4venc_sn.dll64P
adb pull /system/lib/dsp/baseimage.dof ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/baseimage.dof
adb pull /system/lib/dsp/conversions.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/conversions.dll64P
adb pull /system/lib/dsp/h264vdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/h264vdec_sn.dll64P
adb pull /system/lib/dsp/h264venc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/h264venc_sn.dll64P
adb pull /system/lib/dsp/jpegenc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/jpegenc_sn.dll64P
adb pull /system/lib/dsp/m4venc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/m4venc_sn.dll64P
adb pull /system/lib/dsp/mp3dec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mp3dec_sn.dll64P
adb pull /system/lib/dsp/mp4vdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mp4vdec_sn.dll64P
adb pull /system/lib/dsp/mpeg4aacdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mpeg4aacdec_sn.dll64P
adb pull /system/lib/dsp/mpeg4aacenc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/mpeg4aacenc_sn.dll64P
adb pull /system/lib/dsp/nbamrdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/nbamrdec_sn.dll64P
adb pull /system/lib/dsp/nbamrenc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/nbamrenc_sn.dll64P
adb pull /system/lib/dsp/postprocessor_dualout.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/postprocessor_dualout.dll64P
adb pull /system/lib/dsp/ringio.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ringio.dll64P
adb pull /system/lib/dsp/usn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/usn.dll64P
adb pull /system/lib/dsp/wbamrdec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wbamrdec_sn.dll64P
adb pull /system/lib/dsp/wbamrenc_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wbamrenc_sn.dll64P
adb pull /system/lib/dsp/wmadec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wmadec_sn.dll64P
adb pull /system/lib/dsp/wmv9dec_sn.dll64P ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wmv9dec_sn.dll64P
adb pull /system/lib/egl/libeglinfo.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libeglinfo.so
adb pull /system/lib/egl/libEGL_POWERVR_SGX530_125.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_POWERVR_SGX530_125.so
adb pull /system/lib/egl/libgles1_texture_stream.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgles1_texture_stream.so
adb pull /system/lib/egl/libgles2_texture_stream.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgles2_texture_stream.so
adb pull /system/lib/egl/libGLESv1_CM_POWERVR_SGX530_125.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_POWERVR_SGX530_125.so
adb pull /system/lib/egl/libGLESv2_POWERVR_SGX530_125.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_POWERVR_SGX530_125.so
adb pull /system/lib/hw/audio.primary.omap3.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/audio.primary.omap3.so
adb pull /system/lib/hw/gps.milestone2.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gps.milestone2.so
adb pull /system/lib/hw/gralloc.omap3.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gralloc.omap3.so
adb pull /system/lib/libarcsoft.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libarcsoft.so
adb pull /system/lib/libaudio.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libaudio.so
adb pull /system/lib/libbattd.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libbattd.so
adb pull /system/lib/libbayercamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libbayercamera.so
adb pull /system/lib/libcaps.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcaps.so
adb pull /system/lib/libcryptoki.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libcryptoki.so
adb pull /system/lib/libganril.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libganril.so
adb pull /system/lib/libgki.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libgki.so
adb pull /system/lib/libglslcompiler.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libglslcompiler.so
adb pull /system/lib/libHPImgApi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libHPImgApi.so
adb pull /system/lib/libIMGegl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libIMGegl.so
adb pull /system/lib/libmotdb.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmotdb.so
adb pull /system/lib/libmotodbgutils.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmotodbgutils.so
adb pull /system/lib/libmsl_interface.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libmsl_interface.so
adb pull /system/lib/liboemcamera.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/liboemcamera.so
adb pull /system/lib/libOMX.TI.720P.Decoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libOMX.TI.720P.Decoder.so
adb pull /system/lib/libOMX.TI.720P.Encoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libOMX.TI.720P.Encoder.so
adb pull /system/lib/libOMX.TI.h264.splt.Encoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libOMX.TI.h264.splt.Encoder.so
adb pull /system/lib/libOMX.TI.mp4.splt.Encoder.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libOMX.TI.mp4.splt.Encoder.so
adb pull /system/lib/libpvr2d.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libpvr2d.so
adb pull /system/lib/libpvrANDROID_WSEGL.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libpvrANDROID_WSEGL.so
adb pull /system/lib/libPVRScopeServices.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libPVRScopeServices.so
adb pull /system/lib/libril-moto-umts-1.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libril-moto-umts-1.so
adb pull /system/lib/librilswitch.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/librilswitch.so
adb pull /system/lib/libsmapi.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsmapi.so
adb pull /system/lib/libsmiledetect.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsmiledetect.so
adb pull /system/lib/libsrv_init.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsrv_init.so
adb pull /system/lib/libsrv_um.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsrv_um.so
adb pull /system/lib/libssmgr.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libssmgr.so
adb pull /system/lib/libtpa_core.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libtpa_core.so
adb pull /system/lib/libtpa.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libtpa.so
adb pull /system/lib/libusc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libusc.so
adb pull /system/lib/modules/act_gact.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/act_gact.ko
adb pull /system/lib/modules/act_mirred.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/act_mirred.ko
adb pull /system/lib/modules/act_police.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/act_police.ko
adb pull /system/lib/modules/cls_u32.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/cls_u32.ko
adb pull /system/lib/modules/dummy.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/dummy.ko
adb pull /system/lib/modules/em_u32.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/em_u32.ko
adb pull /system/lib/modules/ifb.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/ifb.ko
adb pull /system/lib/modules/kineto_gan.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/kineto_gan.ko
adb pull /system/lib/modules/modem_pm_driver.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/modem_pm_driver.ko
adb pull /system/lib/modules/netmux.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/netmux.ko
adb pull /system/lib/modules/netmux_linkdriver.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/netmux_linkdriver.ko
adb pull /system/lib/modules/output.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/output.ko
adb pull /system/lib/modules/pcbc.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pcbc.ko
adb pull /system/lib/modules/sch_htb.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sch_htb.ko
adb pull /system/lib/modules/sch_ingress.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sch_ingress.ko
adb pull /system/lib/modules/sec.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/sec.ko
adb pull /system/lib/modules/tiap_drv.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tiap_drv.ko
adb pull /system/lib/modules/tiwlan_drv.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/tiwlan_drv.ko
adb pull /system/lib/modules/wl127x_test.ko ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/wl127x_test.ko
adb pull /system/media/audio/ringtones/Moto.ogg ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Moto.ogg

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Proprietary libraries required to build open source libraries
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libarcsoft.so:obj/lib/libarcsoft.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:obj/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsmiledetect.so:obj/lib/libsmiledetect.so

# All the blobs necessary for milestone2
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/akmd2:system/bin/akmd2 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ap_gain.bin:system/bin/ap_gain.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/battd:system/bin/battd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/brcm_guci_drv:system/bin/brcm_guci_drv \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/charge_only_mode:system/bin/charge_only_mode \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gkisystem:system/bin/gkisystem \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/location:system/bin/location \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/nvm_daemon:system/bin/nvm_daemon \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/opprofdaemon:system/bin/opprofdaemon \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/protocol_driver:system/bin/protocol_driver \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/pvrsrvinit:system/bin/pvrsrvinit \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ssmgrd:system/bin/ssmgrd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usbd:system/bin/usbd \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/cameraCalFileDef5M.bin:system/etc/cameraCalFileDef5M.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/cameraCalFileDef8M.bin:system/etc/cameraCalFileDef8M.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wl1271.bin:system/etc/firmware/wl1271.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fmc_init_1273.2.bts:system/etc/fmc_init_1273.2.bts \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fmc_init_6450.2.bts:system/etc/fmc_init_6450.2.bts \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fm_rx_init_1273.2.bts:system/etc/fm_rx_init_1273.2.bts \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fm_rx_init_6450.2.bts:system/etc/fm_rx_init_6450.2.bts \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mot_ise_imager_cfg.bin:system/etc/mot_ise_imager_cfg.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ap_flex_version.txt:system/etc/motorola/ap_flex_version.txt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio:system/etc/motorola/bp_nvm_default/File_Audio \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio1_AMR_WB:system/etc/motorola/bp_nvm_default/File_Audio1_AMR_WB \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio2:system/etc/motorola/bp_nvm_default/File_Audio2 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio2_AMR_WB:system/etc/motorola/bp_nvm_default/File_Audio2_AMR_WB \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio3:system/etc/motorola/bp_nvm_default/File_Audio3 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio3_AMR_WB:system/etc/motorola/bp_nvm_default/File_Audio3_AMR_WB \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio4:system/etc/motorola/bp_nvm_default/File_Audio4 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio4_AMR_WB:system/etc/motorola/bp_nvm_default/File_Audio4_AMR_WB \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio5:system/etc/motorola/bp_nvm_default/File_Audio5 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio5_AMR_WB:system/etc/motorola/bp_nvm_default/File_Audio5_AMR_WB \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio6:system/etc/motorola/bp_nvm_default/File_Audio6 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio7:system/etc/motorola/bp_nvm_default/File_Audio7 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Audio8:system/etc/motorola/bp_nvm_default/File_Audio8 \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_GPRS:system/etc/motorola/bp_nvm_default/File_GPRS \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_GSM:system/etc/motorola/bp_nvm_default/File_GSM \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Logger:system/etc/motorola/bp_nvm_default/File_Logger \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_Seem_Flex_Tables:system/etc/motorola/bp_nvm_default/File_Seem_Flex_Tables \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/File_UMA:system/etc/motorola/bp_nvm_default/File_UMA \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/commdrv_fs.sh:system/etc/motorola/comm_drv/commdrv_fs.sh \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mmins_cust_emergency_number.cfg:system/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mmins_settings.cfg:system/etc/motorola/comm_drv/mmins_settings.cfg \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mmins_telephony.cfg:system/etc/motorola/comm_drv/mmins_telephony.cfg \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mmins_user_settings.cfg:system/etc/motorola/comm_drv/mmins_user_settings.cfg \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/plmn_text_table.bin:system/etc/motorola/comm_drv/plmn_text_table.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/PLMN_VERSION.txt:system/etc/motorola/comm_drv/PLMN_VERSION.txt \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fw_tiwlan_ap.bin:system/etc/wifi/fw_tiwlan_ap.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fw_tiwlan_ap_rfmd.bin:system/etc/wifi/fw_tiwlan_ap_rfmd.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/fw_wlan1271.bin:system/etc/wifi/fw_wlan1271.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/com.motorola.android.location.jar:system/framework/com.motorola.android.location.jar \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/720p_h264vdec_sn.dll64P:system/lib/dsp/720p_h264vdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/720p_h264venc_sn.dll64P:system/lib/dsp/720p_h264venc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/720p_mp4vdec_sn.dll64P:system/lib/dsp/720p_mp4vdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/720p_mp4venc_sn.dll64P:system/lib/dsp/720p_mp4venc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/baseimage.dof:system/lib/dsp/baseimage.dof \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/conversions.dll64P:system/lib/dsp/conversions.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/h264vdec_sn.dll64P:system/lib/dsp/h264vdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/h264venc_sn.dll64P:system/lib/dsp/h264venc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/jpegenc_sn.dll64P:system/lib/dsp/jpegenc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/m4venc_sn.dll64P:system/lib/dsp/m4venc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mp3dec_sn.dll64P:system/lib/dsp/mp3dec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mp4vdec_sn.dll64P:system/lib/dsp/mp4vdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mpeg4aacdec_sn.dll64P:system/lib/dsp/mpeg4aacdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/mpeg4aacenc_sn.dll64P:system/lib/dsp/mpeg4aacenc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/nbamrdec_sn.dll64P:system/lib/dsp/nbamrdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/nbamrenc_sn.dll64P:system/lib/dsp/nbamrenc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/postprocessor_dualout.dll64P:system/lib/dsp/postprocessor_dualout.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ringio.dll64P:system/lib/dsp/ringio.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/usn.dll64P:system/lib/dsp/usn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wbamrdec_sn.dll64P:system/lib/dsp/wbamrdec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wbamrenc_sn.dll64P:system/lib/dsp/wbamrenc_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wmadec_sn.dll64P:system/lib/dsp/wmadec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wmv9dec_sn.dll64P:system/lib/dsp/wmv9dec_sn.dll64P \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libeglinfo.so:system/lib/egl/libeglinfo.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_POWERVR_SGX530_125.so:system/lib/egl/libEGL_POWERVR_SGX530_125.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgles1_texture_stream.so:system/lib/egl/libgles1_texture_stream.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgles2_texture_stream.so:system/lib/egl/libgles2_texture_stream.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_POWERVR_SGX530_125.so:system/lib/egl/libGLESv1_CM_POWERVR_SGX530_125.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_POWERVR_SGX530_125.so:system/lib/egl/libGLESv2_POWERVR_SGX530_125.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio.primary.omap3.so:system/lib/hw/audio.primary.omap3.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gps.milestone2.so:system/lib/hw/gps.milestone2.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gralloc.omap3.so:system/lib/hw/gralloc.omap3.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libarcsoft.so:system/lib/libarcsoft.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libaudio.so:system/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libbattd.so:system/lib/libbattd.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libbayercamera.so:system/lib/libbayercamera.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcaps.so:system/lib/libcaps.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libcryptoki.so:system/lib/libcryptoki.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libganril.so:system/lib/libganril.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libgki.so:system/lib/libgki.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libglslcompiler.so:system/lib/libglslcompiler.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libHPImgApi.so:system/lib/libHPImgApi.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libIMGegl.so:system/lib/libIMGegl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmotdb.so:system/lib/libmotdb.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmotodbgutils.so:system/lib/libmotodbgutils.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libmsl_interface.so:system/lib/libmsl_interface.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/liboemcamera.so:system/lib/liboemcamera.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOMX.TI.720P.Decoder.so:system/lib/libOMX.TI.720P.Decoder.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOMX.TI.720P.Encoder.so:system/lib/libOMX.TI.720P.Encoder.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOMX.TI.h264.splt.Encoder.so:system/lib/libOMX.TI.h264.splt.Encoder.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libOMX.TI.mp4.splt.Encoder.so:system/lib/libOMX.TI.mp4.splt.Encoder.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libpvr2d.so:system/lib/libpvr2d.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libril-moto-umts-1.so:system/lib/libril-moto-umts-1.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/librilswitch.so:system/lib/librilswitch.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsmapi.so:system/lib/libsmapi.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsmiledetect.so:system/lib/libsmiledetect.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsrv_init.so:system/lib/libsrv_init.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsrv_um.so:system/lib/libsrv_um.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libssmgr.so:system/lib/libssmgr.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libtpa_core.so:system/lib/libtpa_core.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libtpa.so:system/lib/libtpa.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libusc.so:system/lib/libusc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/act_gact.ko:system/lib/modules/act_gact.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/act_mirred.ko:system/lib/modules/act_mirred.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/act_police.ko:system/lib/modules/act_police.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/cls_u32.ko:system/lib/modules/cls_u32.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/dummy.ko:system/lib/modules/dummy.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/em_u32.ko:system/lib/modules/em_u32.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/ifb.ko:system/lib/modules/ifb.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/kineto_gan.ko:system/lib/modules/kineto_gan.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/modem_pm_driver.ko:system/lib/modules/modem_pm_driver.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/netmux.ko:system/lib/modules/netmux.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/netmux_linkdriver.ko:system/lib/modules/netmux_linkdriver.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/output.ko:system/lib/modules/output.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/pcbc.ko:system/lib/modules/pcbc.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sch_htb.ko:system/lib/modules/sch_htb.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sch_ingress.ko:system/lib/modules/sch_ingress.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/sec.ko:system/lib/modules/sec.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tiap_drv.ko:system/lib/modules/tiap_drv.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/tiwlan_drv.ko:system/lib/modules/tiwlan_drv.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/wl127x_test.ko:system/lib/modules/wl127x_test.ko \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/Moto.ogg:system/media/audio/ringtones/Moto.ogg

# All the apks necessary for milestone2
PRODUCT_PACKAGES += \\
    AudioEffectSettings \\
    CompassCalibrate \\
    MotoPhonePortal

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),milestone2)
LOCAL_PATH:=\$(call my-dir)

# Module makefile rules for apks on milestone2

# AudioEffectSettings

include \$(CLEAR_VARS)

LOCAL_MODULE := AudioEffectSettings
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# CompassCalibrate

include \$(CLEAR_VARS)

LOCAL_MODULE := CompassCalibrate
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

# MotoPhonePortal

include \$(CLEAR_VARS)

LOCAL_MODULE := MotoPhonePortal
LOCAL_SRC_FILES := \$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)

endif

EOF

./setup-makefiles.sh
