#!/bin/sh
#
# Pre-Squish a CM otapackage for distribution
# cyanogen / Milestone2
#

echo "CH package:"
CM_VARIANT=ch
if [ -f $ANDROID_BUILD_TOP/device/motorola/milestone2/releasetools/squisher ]; then
        . $ANDROID_BUILD_TOP/device/motorola/milestone2/releasetools/squisher
fi

echo "EU package:"
CM_VARIANT=eu
if [ -f $ANDROID_BUILD_TOP/device/motorola/milestone2/releasetools/squisher ]; then
        . $ANDROID_BUILD_TOP/device/motorola/milestone2/releasetools/squisher
fi

exit 0
