#!/system/bin/sh
#export PATH=/system/bin:/system/xbin:$PATH
#mount -o remount,rw /system
#
#if [ -e /proc/device-tree/System@0/Keypad@0/name ]; then
#	keypad_name=`cat /proc/device-tree/System@0/Keypad@0/name`
#	#keypad_type=`getprop persist.sys.keypad_type`
#	keypad_type="qwerty"
#	if [ "x$keypad_name" != "x" ]; then
#		ln -fs /system/usr/keylayout/$keypad_name-$keypad_type.kl /system/usr/keylayout/qwerty.kl
#		rm -f /system/usr/keychars/qwerty.kcm.bin
#		ln -fs /system/usr/keychars/$keypad_name-$keypad_type.kcm.bin /system/usr/keychars/qwerty.kcm.bin
#	fi
#fi
#mount -o remount,ro /system
