#!/system/bin/sh
#
# load multitouch module

# Module location
MODULE="/system/lib/modules/qtouch_num.ko"

# Max number of fingers
MAX_TOUCH=`getprop persist.sys.qtouch_num`

# Load the module if MAX_TOUCH > 2
if [ -n "$MAX_TOUCH" ]; then
  modprobe -r $MODULE 2>/dev/null
  if [ $MAX_TOUCH -gt 2 ]; then
	insmod $MODULE
	echo $MAX_TOUCH > /proc/qtouch/num_touch
  fi
fi

