#!/system/bin/sh
#
# load multitouch module

# Module location
MODULE="/system/lib/modules/qtouch_num.ko"

# Max number of fingers
MAX_TOUCH=`getprop persist.sys.qtouch_num`
if [ -z "$MAX_TOUCH" ]; then
    MAX_TOUCH=2
fi

# Load the module
insmod $MODULE
echo $MAX_TOUCH > /proc/qtouch/num_touch