#!/system/bin/sh
#

# Max number of fingers
MAX_TOUCH=`getprop persist.sys.qtouch_num`
if [ -z "$MAX_TOUCH" ]; then
    MAX_TOUCH=2
fi

# Load the module
#insmod $MODULE
echo $MAX_TOUCH > /proc/multitouch/num
